### ISSUE TITLE
`snap run corebird` and `snap run corebird-diddledan` don't do anything

### ISSUE THREAD

**Issue by Ads20000** [diddledan/corebird-snap#1]
Really, it should be possible for me to run the Corebird Snap using one of these commands?

````
$ snap run corebird
error: cannot find current revision for snap corebird: readlink /snap/corebird/current: no such file or directory
$ snap run corebird-diddledan
error: cannot find app "corebird-diddledan" in "corebird-diddledan"
````

**Comment by diddledan** [comment]
try:

`$ snap run corebird-diddledan.corebird`

**Comment by Ads20000** [comment]
That works thanks!
If we asked the Corebird upstream to use your `snapcraft.yaml` to make their own Snap to put in the Snappy Store under the `corebird` name, presumably it would run with just `snap run corebird`?

**Comment by diddledan** [comment]
I believe so, yes, they'll be allowed to use the corebird name and as the binary will then be the same as the snap name then it should not need the format snapname.binaryname which is needed by this one.

**Comment by diddledan** [comment]
There is now a corebird snap which I maintain under the name directly, rather than with a suffix. You can now run `snap install corebird` and then `snap run corebird` will work properly. I've unpublished `corebird-diddledan` now in favour of `corebird` so I recommend you switch to using the new package name - this will mean your settings will be lost :-(

**Comment by Ads20000** [comment]
@diddledan Great! Maybe add baedert as a collaborator when [this feature](https://forum.snapcraft.io/t/ux-for-snap-collaboration/86/20) is released? :)

**Comment by Ads20000** [comment]
@diddledan Also (if there's something in this, I could file a new issue), would it be possible to cut down on the file size somehow? Do we need *all* of those dependencies? You can include dependencies as parts if maybe it's possible that you can get slimmed-down bits of them rather than pulling the full Debian packages. [Peek did it the latter way.](https://github.com/phw/peek/blob/master/snapcraft.yaml)

**Comment by Ads20000** [comment]
Moved to #3
