### ISSUE TITLE
Can't seem to use Twitter with Corebird

### ISSUE THREAD

**Issue by Ads20000** [diddledan/corebird-snap#2]
Using the launcher in the Dash to open Corebird instead of a `snap run` command, I get this and it's not clear what to do with it.
![screenshot from 2017-04-12 15-43-28](https://cloud.githubusercontent.com/assets/3178485/24964040/163fed80-1f98-11e7-8ed4-811e54b91de5.png)

**Comment by diddledan** [comment]
That is a documentation issue for upstream. I am not a developer of Corebird and only packaged it into a snap. Therefore I did not change any behaviour. The step to proceed is to click the "request pin" button which should open a new browser window to login and get a pin which you paste into the input box and then click "confirm".

**Comment by Ads20000** [comment]
Ah that's fine, it didn't open a new browser window though

**Comment by diddledan** [comment]
aha, now not opening a browser is a bug. Unfortunately, it's difficult to communicate ahead of installation, but you need to have `snapd-xdg-open` installed on your host system (via apt) before browser windows can be opened by any snap:

`sudo apt install snapd-xdg-open`

**Comment by Ads20000** [comment]
Ahhhh I was wondering if there was a packages like the one for Flatpak. Cheers! :)

**Comment by Ads20000** [comment]
Of course ideally this should just work without a Deb package but that's for upstream to resolve
